name: Build Flutter Windows App

on:
  push:
    branches:
      - windows-build
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/windows/runner/Release/
